import Link from 'next/link'
import { SITE_NAME, GITHUB_URL } from '@/lib/constants'
import { Github, Shield } from 'lucide-react'

export default function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="bg-dark-900 border-t border-dark-700 mt-16 py-8 no-print">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* About */}
          <div>
            <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center space-x-2">
              <Shield className="w-5 h-5 text-primary-500" />
              <span>{SITE_NAME}</span>
            </h3>
            <p className="text-sm text-muted-foreground">
              Real-time cybersecurity threat intelligence aggregator with AI-powered summaries.
              Stay informed about the latest vulnerabilities, exploits, and security updates.
            </p>
          </div>

          {/* Links */}
          <div>
            <h3 className="text-lg font-semibold text-foreground mb-4">Quick Links</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="/" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/search" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  Search
                </Link>
              </li>
              <li>
                <Link href="/iocs" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  IOC Lookup
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  Contact Us
                </Link>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h3 className="text-lg font-semibold text-foreground mb-4">Legal</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="/privacy" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className="text-muted-foreground hover:text-primary-500 transition-colors">
                  Terms of Service
                </Link>
              </li>
              <li>
                <a 
                  href={GITHUB_URL} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-muted-foreground hover:text-primary-500 transition-colors inline-flex items-center space-x-1"
                >
                  <Github className="w-4 h-4" />
                  <span>GitHub</span>
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="mt-8 pt-8 border-t border-dark-700 text-center text-sm text-muted-foreground">
          <p>© {currentYear} {SITE_NAME}. All rights reserved.</p>
          <p className="mt-2">
            Data aggregated from various public sources. Summaries generated by AI.
          </p>
        </div>
      </div>
    </footer>
  )
}

